# Generated by Django 2.1.2 on 2018-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181120_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
